### ISSUE TITLE
vnc asks for password

### ISSUE THREAD

**Issue by atrebbi** [jgoerzen/docker-dos-bbs#1]
on a macOS, when trying to connect with vnc on docker remapped port, the server seems to ask for a password that i can't find in docs

**Comment by jgoerzen** [comment]
Hi,

The README.md in docker-dos-bbs says to refer to
https://github.com/jgoerzen/docker-dosemu for more information.  It
notes:

VNCPASSWORD can set the password for the VNC console (maximum 8
characters, a limitation of tightvncserver). If you do not set one, a
random password will be assigned on each start of the container, and
logged in the docker logs.

Does this address the issue for you?

**Comment by atrebbi** [comment]
yes, thanks, it was in the logs:
2019-10-09 19:53:53,004 DEBG 'vncserver' stdout output:
 *** VNC password for this session: ******
thanks
